apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclic-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-petclic
  template:
    metadata:
      labels:
        app: spring-petclic
    spec:
      containers:
      - name: spring-petclic
        image: bhanuchandar6/spring-petclic:latest
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: spring-petclic-service
spec:
  selector:
    app: spring-petclic
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
